## 异常体系

Java 把所有的非正常情况分成两种：异常（Exception）和错误（Error），它们都继承 Throwable 父类

异常的体系：

```java
--| Throwable   所有异常或者错误类的超类
----| Error     错误 错误一般是用于jvm或者是硬件引发的问题，所以我们一般不会通过代码去处理错误的。
----| Exception 异常 是需要通过代码去处理的。
```

> 如何区分错误与异常：
>
> + 如果程序出现了不正常的信息，如果不正常的信息的类名是以`Error`结尾的，那么肯定是一个错误。
> + 如果是以`Exception`结尾的，那么肯定就是一个异常。
>
> 

Throwable构造器

+ Throwable()
+ Throwable(String message)
+ Throwable(Throwable cause)
+ Throwable(String message, Throwable cause)：构造一个带指定详细消息（以后通过 getMessage() 方法获取）和原因（以后通过 getCause() 方法获取）的新 throwable



Throwable常用的方法：

+ `toString()`  返回当前异常对象的`完整类名+异常或错误信息`。
+ `getMessage()` 返回的是创建Throwable传入的字符串信息
+ `printStackTrace()` 打印异常的栈信息。

```java
class Demo {
	public static void main(String[] args) {
		
		// 创建了一个Throwable对象。
		Throwable t = new Throwable("头晕，感冒..");
        
		String info = t.toString();
		String message = t.getMessage();
        
        // java.lang.Throwable  包名+类名 = 完整类名
		System.out.println("toString: "+ info);  
		System.out.println("message: "+ message);
		
		test();
	}

	public static void test(){
		Throwable t = new Throwable();
		t.printStackTrace();
	}
}
```



## 异常处理

### 捕获处理

如果执行 try 块里的代码时出现异常，Java 运行时环境收到异常对象后，会寻找能处理该异常对象的 catch 块，如果找到合适的 catch 块，则**把该异常对象交给该 catch 块处理**，这个过程被称为捕获异常

如果 Java 运行时环境找不到捕获该异常的 catch 块，则使用全局默认的`DefaultUncaughtExceptionHandler`（处理方式是 `e.printStackTrace(System.err)`），然后运行时环境终止，该**线程**也将退出

捕获处理的格式：

```java
try{
	// 可能发生异常的代码；

}catch(捕获的异常类型 变量名){
	// 处理异常的代码....
}
```

捕获处理要注意的细节：

+ 如果`try块`中代码出了异常经过了处理之后，那么`try-catch`块外面的代码可以`正常执行`。
+ 如果`try块`中出了异常的代码，那么在`try块`中出现异常代码后面的代码是`不会执行了`。
+ 一个try块后面是可以跟有多个`catch块`的，也就是一个try块可以捕获多种异常的类型。
+ 一个try块`可以捕获多种异常的类型`,但是捕获的异常类型必须从`小到大进行捕获`，否则编译报错。



> 疑问： 以后捕获处理的时候是否就是捕获Exception即可？
>
> + 错的，因为我们在现实开发中遇到不同的异常类型的时候，往往会有不同 的处理方式。
>   所以要分开不同的异常类型处理。

```java
class Demo {
	public static void main(String[] args) {
		int[] arr = null;
		div(4,0,arr);
	}

	public static void div(int a , int b,int[] arr){
		int c = 0;
		try{
			c = a/b; // jvm在这句话的时候发现了不正常的情况，那么就会创建一个对应的异常对象。
			System.out.println("数组的长度："+ arr.length);
		}catch(ArithmeticException e){
			// 处理异常的代码....
			System.out.println("异常处理了....");
			System.out.println("toString:"+ e.toString());
		}catch(NullPointerException e){
			System.out.println("出现了空指针异常....");
		}catch(Exception e){  
			System.out.println("我是急诊室，包治百病！");
		}
		System.out.println("c="+c);
	}
}
```

> 疑问：下面的信息是通过`printStackTrace`方法打印出来，那么异常对象从何而来呢？ 
>
> + Exception in thread "main" java.lang.ArithmeticException: / by zero
>   at Demo.div(Demo.java:10)
>   at Demo.main(Demo.java:5)
> + jvm运行到a/b这个语句的时候，发现b为0，除数为0在我们现实生活中是属于不正常的情况，jvm一旦发现了这种不正常的情况时候，那么jvm就会马上创建一个对应的异常对象，并且会调用这个异常对象的`printStackTrace`的方法来处理。
> + 当程序运行出现异常，**系统会自动生成一个异常对象**，该异常对象被提交给 Java 运行时环境，这个过程被称为抛出（throw）异常



### 抛出处理

抛出处理---`throw`， `throws`

抛出处理要注意的细节：

+ 如果一个`方法的内部抛出`了一个异常对象，那么必须要在`方法上声明抛出`。
+ 如果调用了一个声明抛出异常的方法，那么`调用者必须要处理`异常。
+ 如果一个方法内部抛出了一个异常对象，那么`throw语句`后面的代码都`不会再执行`了（一个方法遇到了throw关键字，该方法也会马上停止执行的）。

`throw`与`throws`两个关键字：

+ throw关键字是用于`方法内部`抛出一个异常对象的
+ throws关键字是用于在`方法声明`上声明抛出异常类型的。
+ throw关键字后面`只能有一个异常对象`
+ throws后面一次`可以声明抛出多种类型的异常`。

> 疑问：何时使用抛出处理？何时捕获处理？原则是如何？
>
> + 如果你需要通知到调用者，你代码出了问题，那么这时候就使用抛出处理.
> + 如果代码是直接与用户打交道遇到了异常千万不要再抛，再抛的话，就给了用户了。
>   这时候就应该使用捕获处理。



## finally 块

`finally`块的 使用前提是必须要存在`try块`才能使用。

`finally块的代码在任何情况下都会执行的`，除了jvm退出的情况。

- 当程序执行 try 块、catch 块时遇到 `return` 或 `throw` 语句时，系统不会立即结束该方法，而是去寻找该异常处理流程中是否包含 `finally 块`
- 如果有 finally 块，系统立即开始执行 finally 块——只有当 finally 块执行完成后，系统才会再次跳回来执行 try 块、catch 块里的 return 或 throw 语句；
- 如果 finally 块里也使用了 return 或 throw 等导致方法终止的语句，finally 块已经终止了方法，系统将不会跳回去执行 try 块、catch 块里的任何代码

```java
class Demo {
	public static void main(String[] args) {
		div(4,0);
	}
	public static void div(int a, int b){
		try{
			if(b==0){
				System.exit(0); // 退出jvm
			}
			int c = a/b;
			System.out.println("c="+ c);
		}catch(Exception e){
			System.out.println("出了除数为0的异常...");
			throw e;
		}finally{
			System.out.println("finall块的代码执行了..");
		}
	}
}
```



try块的三种组合方式：

+ 第一种： 比较适用于有异常要处理，但是没有资源要释放的。

  ```java
  try{
  	// 可能发生异常的代码
  }catch(捕获的异常类型 变量名){
  	// 处理异常的代码
  }
  ```

+ 第二种：比较适用于既有异常要处理又要释放资源的代码。

  ```java
  try{
  	// 可能发生异常的代码
  	}catch(捕获的异常类型 变量名){
  		// 处理异常的代码
  	}finally{ 
  		// 释放资源的代码;
  }
  ```

+ 第三种： 比较适用于内部抛出的是运行时异常，并且有资源要被释放。

  ```java
  try{
  	// 可能发生异常的代码
  	}finally{ 
  		// 释放资源的代码;
  }
  ```



finally非常适合做资源释放的工作，这样子可以保证资源文件在任何情况下都 会被释放。

```java
// fianlly释放资源的代码
class Demo {
	public static void main(String[] args) {
		FileReader fileReader = null;
		try{
			// 找到目标文件
			File file = new File("f:\\a.txt");
			// 建立程序与文件的数据通道
			fileReader = new FileReader(file);
			// 读取文件
			char[] buf = new char[1024];
			int length = 0; 
			length = fileReader.read(buf);
			System.out.println("读取到的内容："+ new String(buf,0,length));
		}catch(IOException e){
			System.out.println("读取资源文件失败....");
		}finally{
			try{
				// 关闭资源
				fileReader.close();
				System.out.println("释放资源文件成功....");
			}catch(IOException e){
				System.out.println("释放资源文件失败....");
			}
		}
	}
}
```



## 自定义异常类

自定义异常类的步骤：  自定义一个类继承`Exception`即可。

- 自定义 Checked 异常，应继承 `Exception`
- 自定义 Runtime 异常，应继承`RuntimeException`

```java
class NoIpException extends Exception{
	public NoIpException(String message){
		super(message);  //调用了Exception一个参数的构造函数。
	}
}

class Demo {
	public static void main(String[] args) {
		String ip = "192.168.10.100";
		ip = null;
		try{
			feiQ(ip);  // 如果调用了一个声明抛出异常类型的方法，那么调用者必须要处理。
		}catch(NoIpException e){
			e.printStackTrace();
			System.out.println("插网线！");
		}
	}

	public static void feiQ(String ip) throws NoIpException{
		if(ip==null){
			throw new  NoIpException("没有插网线！");
		}
		System.out.println("正常显示好友列表..");
	}
}
```

```java
class NoMoneyException extends Exception {
	public NoMoneyException(String message){
		super(message);
	}
}

class Demo {
	public static void main(String[] args) {
		try{
			eat(9);
		}catch(NoMoneyException e){
			e.printStackTrace();
			System.out.println("跟我洗碗一个月！！");
		}
	}

	public static void eat(int money) throws NoMoneyException{
		if(money<10){
			throw new NoMoneyException("吃霸王餐");
		}
		System.out.println("吃上了香喷喷的地沟油木桶饭!!");
	}
}
```

## 运行时和编译时异常

编译时异常（Checked 异常）：Exception 及其子类，除了 `RuntimeException` 及其子类以外

- 编译器要求`必须处理`的异常，一旦出现这类异常，**必须显式处理**（捕获或抛出），否则编译无法通过
- 常见的编译时异常：
  + ParseException
  + InterruptedException
  + IOException（子类：FileNotFoundException）
  + ClassNotFoundException
  + SQLException

运行时异常（`Runtime` 异常 / `UnChecked` 异常）：RuntimeException 及其`子类`

- 编译器`不要求强制处理`的异常，程序中出现这类异常时，可以不处理
- 常见的运行时异常：
  + ArithmeticException
  + IndexOutOfBoundsException（子类：ArrayIndexOutOfBoundsException
  + StringIndexOutOfBoundsException）
  + NullPointerException
  + ClassCastException
  + IllegalArgumentException（子类：NumberFormatException、IllegalThreadStateException）
  + IllegalMonitorStateException
  + NoSuchElementException
- Java 类库中定义的运行时异常类应由程序员**预检查**来规避，而不是捕获



> 疑问： 为什么java编译器会如此严格要求编译时异常，对运行时异常如此宽松？
>
> + 运行时异常都是可以通过良好的编程习惯去避免，所以java编译器就没有严格要求处理运行时异常。



```java

class Demo {
	public static void main(String[] args) throws InterruptedException {

		int[] arr = null;
		div(4, 0, arr);

		 Object o = new Object();
		 o.wait();
	}
	public static void div(int a , int b ,int[] arr) {
		if(b == 0){
			return;
		}
		int c = a/b;
		System.out.println("c = " + c);

		if(arr!=null){
			System.out.println("数组的长度：" + arr.length);
		}
	}
}
```



## 异常转译和异常链

- `异常转译`：程序先捕获原始异常，然后抛出一个新的业务异常，新的业务异常中包含了对用户的提示信息
- `异常链`：捕获一个异常然后接着抛出另一个异常，并把原始异常信息保存下来

```java
// 工资计算方法
void calSal() throws SalException {
    try {
        ... // 业务逻辑
    } catch (SQLException sqle) {
        ... // 把原始异常记录下来，留给管理员
        // 下面异常中的 message 就是对用户的提示
        throw new SalException("访问底层数据库出现异常");
    } catch (Exception e) {
        ... // 把原始异常记录下来，留给管理员
        // 下面异常中的 message 就是对用户的提示
        throw new SalException("系统出现未知异常");
    }
}

// 定义 SalException 异常类
public class SalException extends Exception {
    public SalException() {
    }
    public SalException(String msg) {
        super(msg);
    }
    // 创建一个可以接受 Throwable 参数的构造器
    public SalException(Throwable t) {
        super(t);
    }
}
```



## Java7 的异常新特性

- 增强的 throw 语句**编译器**会检査 throw 语句抛出异常的**实际类型**，因此**在方法签名中**可以声明抛出该异常对象的实际类型异常
- 多异常捕获使用一个 catch 块捕获多种类型的异常：多种异常类型之间用`竖线`（|） 隔开，异常变量有隐式的` final `修饰，不能被重新赋值
- 自动关闭资源的 try 语句允许在 try 关键字后紧跟一对圆括号，圆括号可以声明、 初始化实现了 `AutoCloseable` 或 `Closeable` 接口的资源实现类对象，try 语句在该语句结束时自动关闭这些资源

```java
try (
    // 声明、初始化两个可关闭的资源
    // try 语句会自动关闭这两个资源
    BufferedReader br = new BufferedReader(new FileReader("AutoCloseTest.java"));
    PrintStream ps = new PrintStream(new FileOutputStream("a.txt"))) {
    // 使用两个资源
    System.out.println(br.readLine());
    ps.println("ixfosa...");
}
```



## 异常处理规则

- 不要过度使用异常：
  - 对于完全已知的错误，应该编写处理这种错误的代码，增加程序的健壮性
  - 对外部的、不能确定和预知的运行时错误才使用异常
- 不要使用过于庞大的 try 块
- 避免使用 Catch All 语句
- 不要忽略捕获到的异常